# Usage example:
#
#   docker stack deploy -c docker-stack.yml api
#   docker stack ls api
#   docker stack rm api
#
version: "3.1"

volumes:
  db:

services:
  // PostgreSQL database
  // https://hub.docker.com/_/postgres
  db:
    image: postgres:10.11-alpine
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
